<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE oXygen:ReusableComponent [
<!ELEMENT oXygen:ReusableComponent (oXygen:ComponentDescription, oXygen:ComponentDefinition)>
<!ATTLIST oXygen:ReusableComponent 
    xmlns:oXygen CDATA #FIXED "http://www.oxygenxml.com/ns/dita/reuse" 
    id CDATA #IMPLIED
    xml:lang CDATA #IMPLIED
    domains CDATA "(topic abbrev-d)                            a(props deliveryTarget)                            (topic equation-d)                            (topic hazard-d)                            (topic hi-d)                            (topic indexing-d)                            (topic markup-d)                            (topic mathml-d)                            (topic pr-d)                            (topic relmgmt-d)                            (topic sw-d)                            (topic svg-d)                            (topic ui-d)                            (topic ut-d)                            (topic markup-d xml-d)    (topic oXygen-reuse-d) "
    class CDATA "- topic/topic oXygen:ReusableComponent/oXygen:ReusableComponent "    
    xmlns:ditaarch CDATA #FIXED "http://dita.oasis-open.org/architecture/2005/"
    ditaarch:DITAArchVersion CDATA #FIXED "1.2" 
    >
<!ELEMENT oXygen:ComponentDescription (#PCDATA)>
<!ATTLIST oXygen:ComponentDescription 
 class CDATA "- topic/title oXygen:ReusableComponent/oXygen:ComponentDescription ">
<!ELEMENT oXygen:ComponentDefinition ANY>
<!ATTLIST oXygen:ComponentDefinition
    class CDATA "- topic/body oXygen:ReusableComponent/oXygen:ComponentDefinition ">

<!ENTITY % dtd PUBLIC "-//OASIS//DTD DITA Topic//EN" "../Topics/Software/topic.dtd">
%dtd;

]>
<oXygen:ReusableComponent id="ReusableComponent_qc3_hqs_bcb">
    <oXygen:ComponentDescription>Autoren</oXygen:ComponentDescription>
    <oXygen:ComponentDefinition>
        <oXygen:ReusableComponent id="ReusableComponent_ngs_jr5_bcb">
            <oXygen:ComponentDescription>Paul Wolski</oXygen:ComponentDescription>
            <oXygen:ComponentDefinition><author id="author-pw">Paul
                Wolski</author></oXygen:ComponentDefinition>
        </oXygen:ReusableComponent>
        <oXygen:ReusableComponent id="ReusableComponent_ngs_jr5_bcb">
            <oXygen:ComponentDescription>Zehnfinger</oXygen:ComponentDescription>
            <oXygen:ComponentDefinition><author id="author-zf"
                >Zehnfinger</author></oXygen:ComponentDefinition>
        </oXygen:ReusableComponent>
    </oXygen:ComponentDefinition>
</oXygen:ReusableComponent>




